### ISSUE TITLE
about the settings in paper

### ISSUE THREAD

**Issue by lai-pf** [postech-ami/CLIP-Actor#3]
I saw the text prompt "Tony Stark wearing blue suit walking forwards"
in this condition, the result of Text2mesh should like this
![image](https://user-images.githubusercontent.com/32856760/188647191-bf3f7c3c-f56b-43f9-ad69-6a15ae1389bd.png)
but I got this , with the default settings of ninja demo in text2mesh 
![image](https://user-images.githubusercontent.com/32856760/188647338-ac4f7849-c093-4d0d-b7d3-eb7103080ecf.png)
can you tell me about the setting of the experiment between Text2mesh and Clip-Actor while using this text promt.

**Comment by Youwang-Kim** [comment]
@lai-pf 
Hi there, we used the default configuration of the Text2Mesh when we get the results.
Please note that there are some randomness in Text2Mesh and CLIP-Actor, mainly during the optimization process. 
Since we did not fix the cuda seed (for __generating the samples__), the gradient computed from your experiment and our paper's result may differ each other.

**Comment by Youwang-Kim** [comment]
Please reopen this issue if you need more help regarding this.
